### ISSUE TITLE
Running the program

### ISSUE THREAD

**Issue by mylesmcm** [gyanz/dssvue#1]
Hey Gyanz, I am trying to run your dssvue python application. I am the lead for HEC-DSSVue and would like to see the work you have done. I have downloaded the pydsstools and have it running in PyCharm sucessfully. However, your dssvue application I could not get to run. I tried running main.py and it terminates successfully, but I am expecting a GUI window to open, and it does not. My console output is shown below:

![image](https://user-images.githubusercontent.com/51373333/68052832-c5d02000-fca7-11e9-8b15-773ca1cd9665.png)

Can you help me get the app to open? You can see on lines 200 through 202 some commented out lines of code. That is my attempt to run the DSSVue class, but it returns the errors shown below:

```
C:\Anaconda3\envs\DssPyVue\python.exe C:/py/DSSPyVue/dssvue/main.py
Traceback (most recent call last):
  File "C:/py/DSSPyVue/dssvue/main.py", line 201, in <module>
    ex = DSSVue()
  File "C:/py/DSSPyVue/dssvue/main.py", line 22, in __init__
    self.add_actions()
  File "C:/py/DSSPyVue/dssvue/main.py", line 32, in add_actions
    '','',None)
  File "C:/py/DSSPyVue/dssvue/main.py", line 50, in createAction
    action.setIcon(QIcon(QtGui.QPixmap(os.path.join(ui_dir,icon))))
NameError: name 'QtGui' is not defined

Process finished with exit code 1
```
![image](https://user-images.githubusercontent.com/51373333/68053050-4000a480-fca8-11e9-9a3d-fe903801c79b.png)

**Comment by gyanz** [comment]
@mylesmcm I think the relative imports are not working as you might have run the main.py directly. Can you import the show command from the dssvue package as follows?
from dssvue.main import show
show(dss_file_path)
